### ISSUE TITLE
script: Create Meeting

### ISSUE THREAD

**Issue by williamkapke** [williamkapke/hookbot#2]
- Update issue OP with filled out template
  - use frontmatter
  - search issues/PRs for agenda labels
- Create Google Doc
- Create Google Calendar Event
- Create Hangout link
- Link issue in YouTube video
- When closed, update YouTube with list of attendees?

Future improvements:
- If no date in frontmatter, add doodle- data is finalized by new comment

**Comment by Fishrock123** [comment]
Currently @rvagg uses https://github.com/rvagg/make-node-meeting, which relies on https://github.com/rvagg/node-meeting-agenda

**Comment by williamkapke** [comment]
hah- I knew he had SOMETHING! It was on my list to ask him. Thanks... I'll check it out now.

**Comment by Fishrock123** [comment]
As a note, I couldn't actually get it to work properly when I tried.
